spring:
  datasource:
    url: jdbc:mysql://localhost/kadaidb?serverTimezone=JST
    username: root
    password: EmptyVergil1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
